### ISSUE TITLE
[PROJECT] Cleanup basic concepts & tests

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1144]
We need a good clean up of basic concepts. And have tests for subsumption.

# Phase 1
- [x] built_in_scalar_value (name is questionable - ints and floats)
- [x] arithmetic_scalar_value ( + product types)
- [x] predeclare wide <arithmetic_scalar_value>

# Phase 2
- [x] arithmetic_simd_value = instance_of_wide
- [x] builtin_simd_value = arithmetic_simd_value && builtin_scalar_value<element_type>
- [x] predeclare logical<built_in_scalar_value>
- [x] predeclare logical<wide<built_in_scalar_value>>
- [x] logical_scalar_value = instance_of_logical && the T inside is built_in_scalar_value
- [x] logical_simd_value   = instance_of_logical && the T inside is built_in_simd_value

# Phase 3

## Updated plan
By trying to remove the complicated and rather redundant `common_compatible` and `common_compatible_value`, @jtlap found out we can get rid of them with a simpler traits and couple of concepts. THe experience seems safer and more controlalble than just doing s/real//. 

 - [x] Use a single `common_value` traits
 - [x] real_* is in fact just requiring < to exist, adapt to make it obvious
 - [x] Remove all real_*
 - [x] Remove all real_*_value concepts as they are useless
 - [x] scalar_value = arithmetic_scalar_value || logical_scalar_value
 - [x] simd_value   = arithmetic_simd_value || logical_simd_value
 - [x] value = scalar_value || simd_value

**Comment by jfalcou** [comment]
Note for later: we need to have product_type types somewhere so we can ask for SIMD product types proper.
This is a use case for complex for ex.

**Comment by jfalcou** [comment]
Merged in 40e4615
