### ISSUE TITLE
[ROADMAP] Long Term Discussions

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1546]
# Architecture Support
 - [ ] [RISC-V](https://github.com/jfalcou/eve/discussions/1547)
 - [ ] [WASM](https://github.com/jfalcou/eve/discussions/1548)
 - [ ] [ARM Endianness support](https://github.com/jfalcou/eve/discussions/1552)
 - [ ] [SVE Finalisation](https://github.com/jfalcou/eve/discussions/1557)

# Compiler Support
 - [ ] [Microsoft Visual Studio](https://github.com/jfalcou/eve/discussions/1550)
 
# Code Quality
 - [ ] [Codegen Testing](https://github.com/jfalcou/eve/discussions/1549)
 - [ ] [Lane API](https://github.com/jfalcou/eve/discussions/1555)
 - [x] [Overload Process](https://github.com/jfalcou/eve/discussions/1316)

# Outreach Goals
 - [ ] [Mimic nvcpp exmaples](https://github.com/jfalcou/eve/discussions/1553)

**Comment by jfalcou** [comment]
# Overload Process (https://github.com/jfalcou/eve/discussions/1316)

## Current Plan
  * PR for the tag_invoke tooling + documentation in isolation. The documentation should also helps fixing [this](https://github.com/jfalcou/eve/issues/1551#issuecomment-1424630921)
  * PR for passing constants to the new tag_invoke
  * PR for temporary adaptation of current decorators to be compatible with the new ones
  * PR for passing algos to the new tag_invoke
  * PRs for passing "high level" math modules to new tag_invoke
  * PRs  for passing all other modules
