### ISSUE TITLE
[BUG] AVX512 Aggregation is not completely supported

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#974]
This issue supersedes #510 and #511.

After the preparatory works from #973 , this is the complete list of tests with issues around aggregation in AVX512.
This list is long but most of the issue seems to emanate from a small number of places and should be fixed by a large swath with minimal effort.

Compilation Errors:
 - [x] unit.api.regular.swizzle.swap_adjacent_groups.exe

Behavior Issues:
 - [x] #1038

More precisely:
 - a large number of ASAN issues stems from the fact set/get don't have any insights on non-wide logical
 - some functions lack a `requires x86_abi<T,N>` which leads to aggregate code going through the wrong place
 - `make` for aggregation calls set instead of using a smarter algorithm using tuple splitting
 - some top_bits related issues leaks into to_logical then into conditional affecting all the predicates and some functions

Each of those is gonna be fixed by small-scale PR that fixes the issue then re-activates the tests they fix.

See also:

#1034 
 - [x] unit.memory.load.aligned.*
 - [x] unit.memory.load.unaligned.*
 - [x] unit.real.core.logical_and.exe
 - [x] unit.real.core.logical_or.exe
 - [x] unit.memory.store.conditional.exe

#980
 - [x] unit.api.regular.wide.exe
 - [x] unit.internals.to_logical.exe
 - [x] unit.internals.top_bits.exe
 - [x] unit.real.core.has_single_bit.exe
 - [x] unit.real.core.is_denormal.exe
 - [x] unit.real.core.is_equal.exe
 - [x] unit.real.core.is_eqz.exe
 - [x] unit.real.core.is_even.exe
 - [x] unit.real.core.is_finite.exe
 - [x] unit.real.core.is_flint.exe
 - [x] unit.real.core.is_gez.exe
 - [x] unit.real.core.is_greater.exe
 - [x] unit.real.core.is_greater_equal.exe
 - [x] unit.real.core.is_gtz.exe
 - [x] unit.real.core.is_imag.exe
 - [x] unit.real.core.is_infinite.exe
 - [x] unit.real.core.is_less.exe
 - [x] unit.real.core.is_less_equal.exe
 - [x] unit.real.core.is_lessgreater.exe
 - [x] unit.real.core.is_lez.exe
 - [x] unit.real.core.is_ltz.exe
 - [x] unit.real.core.is_nan.exe
 - [x] unit.real.core.is_negative.exe
 - [x] unit.real.core.is_nez.exe
 - [x] unit.real.core.is_ngez.exe
 - [x] unit.real.core.is_ngtz.exe
 - [x] unit.real.core.is_nlez.exe
 - [x] unit.real.core.is_nltz.exe
 - [x] unit.real.core.is_normal.exe
 - [x] unit.real.core.is_not_denormal.exe
 - [x] unit.real.core.is_not_equal.exe
 - [x] unit.real.core.is_not_finite.exe
 - [x] unit.real.core.is_not_flint.exe
 - [x] unit.real.core.is_not_greater.exe
 - [x] unit.real.core.is_not_greater_equal.exe
 - [x] unit.real.core.is_not_imag.exe
 - [x] unit.real.core.is_not_less.exe
 - [x] unit.real.core.is_not_less_equal.exe
 - [x] unit.real.core.is_not_nan.exe
 - [x] unit.real.core.is_odd.exe
 - [x] unit.real.core.is_ordered.exe
 - [x] unit.real.core.is_positive.exe
 - [x] unit.real.core.is_pow2.exe
 - [x] unit.real.core.is_unordered.exe
 - [x] unit.api.regular.comparisons.exe 
 - [x] unit.api.regular.logicals.exe
 - [x] unit.api.regular.swap_if.exe
 - [x] unit.api.regular.swizzle.identity.exe
 - [x] unit.api.regular.swizzle.reverse.exe
 - [x] unit.api.regular.swizzle.zero.exe
 - [x] unit.api.regular.swizzle.broadcast_group.exe
 - [x] unit.api.regular.swizzle.broadcast.exe
 - [x] unit.real.core.convert.to_double.exe
 - [x] unit.real.core.convert.to_float.exe
 - [x] unit.real.core.convert.to_int64.exe
 - [x] unit.real.core.convert.to_int32.exe
 - [x] unit.real.core.convert.to_int16.exe
 - [x] unit.real.core.convert.to_int8.exe
 - [x] unit.real.core.convert.to_uint64.exe
 - [x] unit.real.core.convert.to_uint32.exe
 - [x] unit.real.core.convert.to_uint16.exe
 - [x] unit.real.core.convert.to_uint8.exe
 - [x] unit.memory.store.aligned.exe 
 - [x] unit.real.algorithm.maximum.exe
 - [x] unit.real.algorithm.minimum.exe
 
#981 
 - [x] unit.real.core.rotl.exe
 - [x] unit.real.core.rotr.exe
 - [x] unit.real.core.roundscale.exe
 - [x] unit.real.core.fracscale.exe

#991 
 - [x] unit.api.regular.shuffle.slide_right.exe 
 - [x] unit.api.regular.swizzle.slide_left.exe
 - [x] unit.api.regular.swizzle.slide_right.exe
 - [x] unit.api.regular.replace.exe 
 - [x] unit.api.regular.conditional.exe 
 - [x] unit.real.algorithm.scan.exe
 - [x] unit.real.core.lookup.exe
 - [x] unit.real.core.if_else.exe
 - [x] unit.algo.algorithm.find_if_generic.exe
 - [x] unit.algo.algorithm.find_if_not_generic.exe
 - [x] unit.real.core.logical_andnot.exe
 - [x] unit.real.core.logical_not.exe
 - [x] unit.real.core.logical_notand.exe
 - [x] unit.real.core.logical_notor.exe
 - [x] unit.real.core.logical_ornot.exe
 - [x] unit.real.core.logical_xor.exe
 - [x] unit.algo.algorithm.inclusive_scan_to_generic.exe

ULP Issues:
 - [x] unit.real.math.powm1.exe (#986)
 - [x] unit.real.polynomial.legendre.exe (#979)
 - [x] unit.real.polynomial.laguerre.exe (#979)
 - [x] unit.real.special.beta.exe (#987)
 - [x] unit.real.math.sindcosd.exe (#988)

**Comment by jfalcou** [comment]
See also:
- #980
- #981 
- #979

**Comment by jfalcou** [comment]
All done!
